name: magic_ext_oauth
description: A Magic oauth extension to support Magic social login authentication
version: 0.3.4
homepage: https://magic.link
repository: https://github.com/magiclabs/magic-flutter
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  magic_sdk:
    git:
      url: https://github.com/timeless-space/magic-flutter.git
      ref: bugfix/android-anr-due-to-accessing-keystore-on-main-thread
      path: packages/magic_sdk
  uri: ^1.0.0
  flutter_web_auth: ^0.5.0
  crypto: ^3.0.1
  json_annotation: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
